// Auto-generated by scripts/generateGallery.js
window.GALLERY_IMAGES = [
  "pre_wedding_shoot/photo1.PNG",
  "pre_wedding_shoot/photo2.PNG",
  "pre_wedding_shoot/photo3.PNG",
  "pre_wedding_shoot/photo4.PNG",
  "pre_wedding_shoot/photo5.png",
  "pre_wedding_shoot/photo6.PNG",
  "pre_wedding_shoot/photo7.PNG",
  "pre_wedding_shoot/photo8.PNG",
  "pre_wedding_shoot/photo9.PNG",
  "pre_wedding_shoot/photo10.PNG",
  "pre_wedding_shoot/photo10 copy.PNG"
];
