// const fs = require('fs');
// const path = require('path');

// const imgDirCandidate = path.join(__dirname, '..', 'img', 'pre_wedding_shoot');
// const imgDirFallback = path.join(__dirname, '..', 'img');
// const imgDir = fs.existsSync(imgDirCandidate) ? imgDirCandidate : imgDirFallback;
// const outFile = path.join(__dirname, '..', 'js', 'gallery-data.js');

// try {
//   const files = fs.readdirSync(imgDir, { withFileTypes: true })
//     .filter(d => d.isFile())
//     .map(d => d.name)
//     .filter(name => /\.(jpe?g|png|gif|webp|svg)$/i.test(name))
//     .sort();

//   // If we used the fallback img/ directory, exclude common non-gallery files
//   const exclude = new Set(['favicon.png','count_down.JPG','invite.jpg','pp.jpg','ganesh ji.jpg']);
//   const filtered = files.filter(f => !exclude.has(f));

//   const relativePaths = filtered.map(f => {
//     if(path.basename(imgDir) === 'img') return `img/${f}`;
//     return `img/pre_wedding_shoot/${f}`;
//   });
//   const content = `// Auto-generated by scripts/generateGallery.js\nwindow.GALLERY_IMAGES = ${JSON.stringify(relativePaths, null, 2)};\n`;

//   fs.writeFileSync(outFile, content, 'utf8');
//   console.log(`Wrote ${outFile} with ${relativePaths.length} images.`);
// } catch (err) {
//   console.error('Failed to generate gallery data:', err.message);
//   process.exitCode = 1;
// }


const fs = require('fs');
const path = require('path');

const imgDirCandidate = path.join(__dirname, '..', 'pre_wedding_shoot');
// const imgDirFallback = path.join(__dirname, '..', 'img');
const imgDir = fs.existsSync(imgDirCandidate) ;
const outFile = path.join(__dirname, '..', 'js', 'gallery-data.js');

try {
  const files = fs.readdirSync(imgDir, { withFileTypes: true })
    .filter(d => d.isFile())
    .map(d => d.name)
    .filter(name => /\.(jpe?g|png|gif|webp|svg)$/i.test(name))
    .sort();

  // If we used the fallback img/ directory, exclude common non-gallery files
  // const exclude = new Set(['favicon.png','count_down.JPG','invite.jpg','pp.jpg','ganesh ji.jpg']);
  // const filtered = files.filter(f => !exclude.has(f));

  const relativePaths = files.map(f => {
    // if(path.basename(imgDir) === 'pre_wedding_shoot') return `pre_wedding_shoot/${f}`;
    return `pre_wedding_shoot/${f}`;
  });
  const content = `// Auto-generated by scripts/generateGallery.js\nwindow.GALLERY_IMAGES = ${JSON.stringify(relativePaths, null, 2)};\n`;

  fs.writeFileSync(outFile, content, 'utf8');
  console.log(`Wrote ${outFile} with ${relativePaths.length} images.`);
} catch (err) {
  console.error('Failed to generate gallery data:', err.message);
  process.exitCode = 1;
}
