// const fs = require('fs');
// const path = require('path');

// const imgDirCandidate = path.join(__dirname, '..', 'img', 'pre_wedding_shoot');
// const imgDirFallback = path.join(__dirname, '..', 'img');
// const imgDir = fs.existsSync(imgDirCandidate) ? imgDirCandidate : imgDirFallback;
// const outFile = path.join(__dirname, '..', 'js', 'gallery-data.js');

// try {
//   const files = fs.readdirSync(imgDir, { withFileTypes: true })
//     .filter(d => d.isFile())
//     .map(d => d.name)
//     .filter(name => /\.(jpe?g|png|gif|webp|svg)$/i.test(name))
//     .sort();

//   // If we used the fallback img/ directory, exclude common non-gallery files
//   const exclude = new Set(['favicon.png','count_down.JPG','invite.jpg','pp.jpg','ganesh ji.jpg']);
//   const filtered = files.filter(f => !exclude.has(f));

//   const relativePaths = filtered.map(f => {
//     if(path.basename(imgDir) === 'img') return `img/${f}`;
//     return `img/pre_wedding_shoot/${f}`;
//   });
//   const content = `// Auto-generated by scripts/generateGallery.js\nwindow.GALLERY_IMAGES = ${JSON.stringify(relativePaths, null, 2)};\n`;

//   fs.writeFileSync(outFile, content, 'utf8');
//   console.log(`Wrote ${outFile} with ${relativePaths.length} images.`);
// } catch (err) {
//   console.error('Failed to generate gallery data:', err.message);
//   process.exitCode = 1;
// }


const fs = require('fs');
const path = require('path');

// Prefer project-root `pre_wedding_shoot`, fall back to `img/pre_wedding_shoot`.
const rootCandidate = path.join(__dirname, '..', 'pre_wedding_shoot');
// const imgCandidate = path.join(__dirname, '..', 'img', 'pre_wedding_shoot');
let imgDir = null;
let basedirName = null; // used for building relative paths
if (fs.existsSync(rootCandidate)) {
  imgDir = rootCandidate;
  basedirName = 'pre_wedding_shoot';
} else {
  console.error(`Gallery directory not found.`);
  console.error(`Create either:`);
  console.error(`  - ${rootCandidate}`);
  console.error(`or`);
  console.error(`  - ${imgCandidate}`);
  console.error('Then add your gallery images and re-run `npm run gen-gallery`.');
  process.exitCode = 1;
  return;
}
const outFile = path.join(__dirname, '..', 'js', 'gallery-data.js');

try {
  const files = fs.readdirSync(imgDir, { withFileTypes: true })
    .filter(d => d.isFile())
    .map(d => d.name)
    .filter(name => /\.(jpe?g|png|gif|webp|svg)$/i.test(name))
    .sort();

  // User-specified ordered whitelist of files in pre_wedding_shoot
  const desired = [
    'photo1.PNG',
    'photo2.PNG',
    'photo3.PNG',
    'photo4.PNG',
    'photo5.PNG',
    'photo6.PNG',
    'photo7.PNG',
    'photo8.PNG',
    'photo9.PNG',
    'photo10.PNG',
    'photo10 copy.PNG'
  ];

  // Map desired list to existing files (case-sensitive match). Warn for missing files.
  const fileSet = new Set(files);
  const relativePaths = [];
  const missing = [];
  desired.forEach(name => {
    if (fileSet.has(name)) {
      relativePaths.push(`${basedirName}/${name}`);
    } else {
      missing.push(name);
    }
  });

  if (missing.length) {
    console.warn(`generateGallery: ${missing.length} requested files not found in ${imgDir}:`, missing);
    console.warn('Only found and included the existing requested files.');
  }

  const content = `// Auto-generated by scripts/generateGallery.js\nwindow.GALLERY_IMAGES = ${JSON.stringify(relativePaths, null, 2)};\n`;

  fs.writeFileSync(outFile, content, 'utf8');
  console.log(`Wrote ${outFile} with ${relativePaths.length} images.`);
} catch (err) {
  console.error('Failed to generate gallery data:', err.message);
  process.exitCode = 1;
}
